Own.Manager.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace Own.Manager.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

Own.Manager.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace Own.Manager.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

Own.Manager.Web/Controllers/AboutController.cs
using System.Web.Mvc;

namespace Own.Manager.Web.Controllers
{
    public class AboutController : ManagerControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

Own.Manager.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Own.Manager.Web.Controllers
{
    public class HomeController : ManagerControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index_abp()
        {
            return View();
        }
    }
}

Own.Manager.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using Own.Manager.Web.Models.Layout;

namespace Own.Manager.Web.Controllers
{
    public class LayoutController : ManagerControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ILocalizationManager localizationManager,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

Own.Manager.Web/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Own.Manager.Web.Controllers
{
    public class RoleController : ManagerControllerBase
    {
        // GET: Role
        public ActionResult Index()
        {
            return View();
        }
    }
}

Own.Manager.Web/Controllers/UserController.cs
using Abp.Application.Services;
using Own.Manager.User;
using Own.Manager.User.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Own.Manager.Web.Controllers
{
    public class UserController : ManagerControllerBase
    {
        private readonly IUserAppService _userAppService;
        public UserController(IUserAppService userAppService)
        {
            _userAppService = userAppService;
        }
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(ListPageUserInput input)
        {
            var ret = _userAppService.ListPageUsers(input);
            return Json(ret, JsonRequestBehavior.AllowGet);
        }
    }
}

Own.Manager.Web/Views/About/Index.cshtml
@{
    ViewBag.ActiveMenu = "About"; //The menu item will be active for this page.
}
<div>
    <h1><img src="~/images/abp-logo.png" style="padding-right: 10px;" />@string.Format(L("AboutFormat"), "ASP.NET Boilerplate")</h1>
    <p>@Html.Raw(L("About_AspNetBoilerplateDescription"))</p>
    <p>@L("ForMoreInformation"): <a href="http://www.aspnetboilerplate.com"><strong>aspnetboilerplate.com</strong></a>.</p>
</div>

Own.Manager.Web/Views/Home/Index.cshtml
@{
    Layout = null;
}

@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>Manager</title>
    @Styles.Render("~/Scripts/easyui/themes/metro-orange/easyui.css")
    @Styles.Render("~/Scripts/easyui/themes/icon.css", "~/Scripts/easyui/themes/color.css")

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

</head>
<body class="easyui-layout">
    <!--top-->
    <div data-options="region:'north'" style="height: 80px;">
        @*@Html.Partial("_TopBar")*@
        <h1>管理系统</h1>
    </div>
    <!--bottom-->
    <div data-options="region:'south'" style="height: 30px;"></div>

    <div data-options="region:'west',title:'系统菜单'" style="width: 200px;">

        <ul id="menuTree" class="easyui-tree">
            @*<li>
                    <span>系统管理</span>
                    <ul>
                        <li>
                            <span>菜单管理</span>
                            <ul>
                                <li><span><a href="#">菜单列表</a></span></li>
                            </ul>
                        </li>
                        <li>
                            <span>角色管理</span>
                            <ul>
                                <li><span><a href="Role/index">角色列表</a></span></li>
                            </ul>
                        </li>
                        <li>
                            <span>部门管理</span>
                            <ul>
                                <li><span><a href="#">部门列表</a></span></li>
                            </ul>
                        </li>
                    </ul>
                </li>*@
        </ul>
    </div>

    <!--content-->
    <div data-options="region:'center'" style="border:0; background: #eee;">
        <div id="tabs" class="easyui-tabs" data-options="fit:true">
            <div title="欢迎" style="padding:20px;">
                欢迎！
            </div>
        </div>
    </div>

    @Scripts.Render("~/Scripts/jquery-2.1.4.min.js", "~/Scripts/easyui/jquery.easyui.min.js", "~/Scripts/easyui/locale/easyui-lang-zh_CN.js")

    @Scripts.Render("~/js/main.js")
</body>
</html>

Own.Manager.Web/Views/Home/Index_abp.cshtml
@{
//ViewBag.Title = "Index";
}
<div>
    <p class="lead">@L("Home_ThisIsATemplate")</p>
    <div class="row">
        <div class="col-md-4">
            <h3>ASP.NET MVC</h3>
            <p>
                @L("Home_AspNetDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://asp.net/mvc">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>ASP.NET Boilerplate</h3>
            <p>
                @L("Home_AspNetBoilerplateDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://aspnetboilerplate.com">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>@L("Others")</h3>
            <p>
                @L("Home_OtherTools")
            </p>
        </div>
    </div>
</div>

Own.Manager.Web/Views/Layout/_LanguageSelection.cshtml
@model Own.Manager.Web.Models.Layout.LanguageSelectionViewModel
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="@Model.CurrentLanguage.Icon"></i>
        <span>@Model.CurrentLanguage.DisplayName</span>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        @foreach (var language in Model.Languages)
        {
            if (language.Name != Model.CurrentLanguage.Name)
            {
                <li><a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@(Request.Url)"><i class="@language.Icon"></i> @language.DisplayName</a></li>
            }
        }
    </ul>
</li>

Own.Manager.Web/Views/Layout/_TopMenu.cshtml
@using Abp.Collections.Extensions
@using Own.Manager.Web.Views
@model Own.Manager.Web.Models.Layout.TopMenuViewModel
@{
    var calculateMenuUrl = new Func<string, string>((url) =>
    {
        if (string.IsNullOrEmpty(url))
        {
            return ApplicationPath;
        }

        if (UrlChecker.IsRooted(url))
        {
            return url;
        }

        return ApplicationPath + url;
    });
}
@foreach (var menuItem in Model.MainMenu.Items)
{
    <li class="@(Model.ActiveMenuItemName == menuItem.Name ? "active" : "")">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            <a href="@calculateMenuUrl(menuItem.Url)">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
        }
        else
        {
            <a href="" data-toggle="dropdown">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var subMenuItem in menuItem.Items)
                {
                    <li>
                        <a href="@calculateMenuUrl(subMenuItem.Url)">
                            @if (!string.IsNullOrWhiteSpace(subMenuItem.Icon))
                            {
                                <i class="@subMenuItem.Icon"></i>
                            }
                            @subMenuItem.DisplayName
                        </a>
                    </li>
                }
            </ul>
        }
    </li>
}

Own.Manager.Web/Views/Role/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Own.Manager.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>Manager</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name'); //Localizing momentjs
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Own.Manager.Web/Views/Shared/_LayoutMain.cshtml
@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>Manager</title>
    @Styles.Render("~/Scripts/easyui/themes/metro-orange/easyui.css")
    @Styles.Render("~/Scripts/easyui/themes/icon.css", "~/Scripts/easyui/themes/color.css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

</head>
<body>
   
    @RenderBody()

    @Scripts.Render("~/Scripts/jquery-2.1.4.min.js", "~/Scripts/easyui/jquery.easyui.min.js", "~/Scripts/easyui/locale/easyui-lang-zh_CN.js")

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Own.Manager.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> Manager</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
            </ul>
        </div>
    </div>
</div>

Own.Manager.Web/Views/User/Index.cshtml
@{
    ViewBag.Title = "用户管理";
}

<table id="dgUser"></table>

<div id="dgUser_tb">
    <a id="dgUser_tb_btnNew" href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true" iconCls="icon-add">New User</a>
    <a id="dgUser_tb_btnEdit" href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true" iconCls="icon-edit">Edit User</a>

</div>

<div id="dlgAddUser" style="width:500px;">
    <form id="dlgAddUser_form" novalidate style="margin:0;padding:20px 50px">
        <div style="margin-bottom:20px;border-bottom:1px solid #ccc">User Information</div>
        <div style="margin-bottom:10px">
            <input name="firstname" class="easyui-textbox" required label="First Name:" style="width:100%">
        </div>
        <div style="margin-bottom:10px">
            <input name="lastname" class="easyui-textbox" required label="Last Name:" style="width:100%">
        </div>
        <div style="margin-bottom:10px">
            <input name="phone" class="easyui-textbox" required label="Phone:" style="width:100%">
        </div>
        <div style="margin-bottom:10px">
            <input name="email" class="easyui-textbox" required validType="email" label="Email:" style="width:100%">
        </div>
    </form>

</div>
<div id="dlgAddUser_buttons">
    <a id="dlgAddUser_buttons_btnSave" href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-ok" onclick="saveUser()">Save</a>
    <a id="dlgAddUser_buttons_btnClose" href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:$('#dlg').dialog('close')">Cancel</a>
</div>

@section scripts{
    <script src="~/js/user/index.js"></script>
    <script src="~/js/common.js"></script>
}